# Specify the handler(s) for the root logger (defaults to ConsoleHandler)
handlers= java.util.logging.ConsoleHandler

# Set the default logging level for the root logger
.level= FINEST

# Set the default logging level for the console handler
java.util.logging.ConsoleHandler.level = FINEST
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# Optional: Customize the SimpleFormatter format
# java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$s   ] %5$s%6$s%n
# Use a slightly modified format to be closer to what we saw before
java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

# You could also set levels for specific packages, e.g.:
# com.convert2web.level = FINEST 