package com.convert2web;

import java.awt.*;
import java.awt.geom.AffineTransform;
import java.awt.geom.Path2D;
import java.awt.geom.Point2D;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Locale;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import java.util.ArrayList;
import java.util.Deque;
import java.util.ArrayDeque;
import java.awt.geom.PathIterator;

// W3C DOM imports
import org.w3c.dom.Document;
import org.w3c.dom.DOMImplementation;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

// Batik imports
import org.apache.batik.svggen.SVGGraphics2D;
import org.apache.batik.anim.dom.SVGDOMImplementation;
import org.apache.batik.svggen.SVGGraphics2DIOException;
import org.apache.batik.svggen.SVGGeneratorContext;
import org.apache.batik.dom.GenericDOMImplementation;
import org.apache.batik.svggen.DefaultExtensionHandler;
import org.apache.batik.ext.awt.g2d.GraphicContext;
import org.apache.batik.dom.util.DOMUtilities;
import org.apache.batik.svggen.SVGIDGenerator;

// JAXP Transformer imports
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.TransformerException;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.OutputKeys;
import java.io.StringWriter; // Added for DOMUtilities logging
import javax.xml.XMLConstants;
import java.awt.geom.NoninvertibleTransformException; // Needed for concatMatrix adjustment

/**
 * Implementation of GraphicsHandler using Apache Batik to generate SVG output.
 */
public class BatikGraphicsHandler implements GraphicsHandler {
    private static final Logger logger = Logger.getLogger(BatikGraphicsHandler.class.getName());

    // Add a counter for manual ID generation
    private java.util.concurrent.atomic.AtomicLong manualIdCounter = new java.util.concurrent.atomic.AtomicLong(0);
    private static final String DEFAULT_ID_PREFIX = "elt";

    // Helper class to store graphics state
    private static class GraphicsState {
        final AffineTransform transform;
        final Paint paint;
        final Stroke stroke;
        final Shape clip;
        final Path2D.Double currentPath;

        GraphicsState(AffineTransform transform, Paint paint, Stroke stroke, Shape clip, Path2D.Double currentPath) {
            this.transform = transform;
            this.paint = paint;
            this.stroke = stroke;
            this.clip = clip;
            this.currentPath = currentPath;
        }
    }

    private SVGGraphics2D svgGenerator;
    private Document document;
    private Element root;
    private Path2D.Double currentPath;
    private Deque<GraphicsState> stateStack = new ArrayDeque<>();
    private Stack<Path2D.Double> pathStack = new Stack<>();
    private double[] bbox = null; // Store BBox for setting SVG dimensions
    private final double PADDING = 3.0; // Padding
    private double llx, lly, urx, ury; // Bounding box
    private double width, height;
    private SVGGeneratorContext ctx; // Store the context

    // Variables to track path segments for emptiness check
    private int significantSegmentCount = 0;
    private Point2D lastPoint = null;

    // Custom ID generation (keep commented out unless needed)
    // private static class IncrementalIdGenerator implements SVGIDGenerator { ... }

    // Constructor (can be empty or removed if not needed)
    public BatikGraphicsHandler() { }

    // ---> Primary initialization logic <---
    // No @Override here as it doesn't directly implement the interface method
    private void initializeLogic(double llx, double lly, double urx, double ury) {
        this.llx = llx;
        this.lly = lly;
        this.urx = urx;
        this.ury = ury;
        // Ensure width/height are non-negative
        this.width = (urx >= llx) ? urx - llx : 0;
        this.height = (ury >= lly) ? ury - lly : 0;

        logger.log(Level.INFO, "Initializing BatikGraphicsHandler with BBox: ll=({0},{1}), ur=({2},{3}), width={4}, height={5}",
                   new Object[]{llx, lly, urx, ury, width, height});

        DOMImplementation domImpl = GenericDOMImplementation.getDOMImplementation();
        String svgNS = "http://www.w3.org/2000/svg";
        this.document = domImpl.createDocument(svgNS, "svg", null); // Store document

        ctx = SVGGeneratorContext.createDefault(document);
        ctx.setComment("Generated by EPS2SVG (Batik)");
        // ctx.setEmbeddedFontsOn(true);

        svgGenerator = new SVGGraphics2D(ctx, false);

        // ---> Re-apply initial transform to match EPS coordinates (Y-up, origin at llx, lly) internally <--- 
        AffineTransform initialTransform = AffineTransform.getTranslateInstance(0, this.height);
        initialTransform.scale(1, -1);              // Flip Y axis
        initialTransform.translate(-this.llx, -this.lly); // Translate origin so EPS (llx, lly) maps to SVG (0,0) internally
        svgGenerator.setTransform(initialTransform);
        logger.log(Level.INFO, "Initial svgGenerator transform set to: {0}", svgGenerator.getTransform());

        newPath(); // Initialize the first path
        // Set default graphics properties
        svgGenerator.setPaint(Color.BLACK);
        svgGenerator.setStroke(new BasicStroke(1.0f));

        logger.log(Level.FINE, "BatikGraphicsHandler initialized. No initial coordinate flip applied to svgGenerator.");
    }

    // ---> Implement the interface method <---
    @Override
    public void initialize(double[] bbox) {
        if (bbox != null && bbox.length == 4) {
            initializeLogic(bbox[0], bbox[1], bbox[2], bbox[3]);
        } else {
            logger.log(Level.SEVERE, "Invalid bounding box array passed to initialize. Using defaults.");
            initializeLogic(0, 0, 612, 792); // Default values
        }
    }

    @Override
    public void writeToFile(String outputPath) throws IOException, TransformerException {
        if (svgGenerator == null || document == null) {
             throw new IllegalStateException("Handler not initialized before writeToFile.");
         }
        logger.log(Level.FINE, "Writing SVG to file: {0}", outputPath);

        // ---> Get the root element from the svgGenerator itself <--- 
        Element svgRoot = svgGenerator.getRoot();

        if (svgRoot == null) {
             throw new IOException("SVG root element is null in the document.");
         }
        logger.log(Level.FINE, "Obtained SVG root element ({0}) from document", svgRoot.getNodeName());
        inspectBatikDom("Before write");

        // Set final SVG attributes directly on the root element
        // Use the calculated width and height
        // Ensure width/height are non-negative
        double finalWidth = (this.width >= 0) ? this.width : 1; // Use 1 if zero or negative
        double finalHeight = (this.height >= 0) ? this.height : 1; // Use 1 if zero or negative

         svgRoot.setAttributeNS(null, "width", String.format(Locale.US, "%.5f", finalWidth));
         svgRoot.setAttributeNS(null, "height", String.format(Locale.US, "%.5f", finalHeight));

         // ---> Set viewBox to 0 0 width height <---
         String viewBoxValue = String.format(Locale.US, "0 0 %.5f %.5f", finalWidth, finalHeight);
         svgRoot.setAttributeNS(null, "viewBox", viewBoxValue);
         svgRoot.setAttributeNS(null, "preserveAspectRatio", "xMidYMid meet"); // Keep or adjust as needed

        logger.log(Level.INFO, "Set SVG root attributes: width={0}, height={1}, viewBox=[{2}]", new Object[]{finalWidth, finalHeight, viewBoxValue});

        // Add manual IDs (optional, if needed)
        // Ensure ID generation happens AFTER all graphics are drawn but BEFORE serialization
        // addManualIds(svgRoot);

        // ---> Use Batik's DOMUtilities for serialization <--- 
        try (OutputStream os = new FileOutputStream(outputPath);
             Writer writer = new OutputStreamWriter(os, StandardCharsets.UTF_8)) {
            logger.log(Level.FINE, "Serializing SVG DOM using Batik DOMUtilities...");
            // DOMUtilities handles writing the node content
            DOMUtilities.writeNode(svgRoot, writer);
            writer.flush(); // Ensure all content is written
            logger.log(Level.FINE, "SVG file written via DOMUtilities to: {0}", outputPath);
        } catch (IOException e) {
            logger.log(Level.SEVERE, "IO Error writing SVG file using DOMUtilities: " + outputPath, e);
            throw e;
        }
    }

    @Override
    public void newPath() {
        if (currentPath != null && !isCurrentPathEffectivelyEmpty()) {
             logger.log(Level.WARNING, "newPath called with non-empty path - potential drawing loss. Path bounds: {0}", currentPath.getBounds2D());
        }
        currentPath = new Path2D.Double();
        significantSegmentCount = 0;
        lastPoint = null; // Reset last point for emptiness check
        logger.log(Level.FINEST, "newpath");
    }

    @Override
    public void moveTo(double x, double y) {
         // ---> Use RAW EPS coordinates <--- 
         // Point2D svgPt = transformEpsToSvg(x, y); // Removed
        if (currentPath == null) { // Ensure path exists
             logger.log(Level.WARNING, "moveTo called before path initialized. Creating new path.");
             newPath();
         }
        currentPath.moveTo(x, y); // Use raw x, y
        lastPoint = new Point2D.Double(x, y); // Update lastPoint with raw EPS coordinates
        significantSegmentCount = 0; // Reset segment count on moveto
        logger.log(Level.FINEST, "moveto: Raw ({0}, {1}) passed directly", new Object[]{x, y});
    }

    @Override
    public void lineTo(double x, double y) {
        // ---> Use RAW EPS coordinates <--- 
        // Point2D svgPt = transformEpsToSvg(x, y); // Removed
        if (currentPath == null) {
             logger.log(Level.WARNING, "lineTo called before path initialized. Creating new path and moving to point.");
             newPath();
             currentPath.moveTo(x, y); // Use raw x, y
             significantSegmentCount = 0;
             lastPoint = new Point2D.Double(x, y); // Store raw EPS
             return;
         }
        if (currentPath.getCurrentPoint() == null) {
            logger.log(Level.WARNING, "lineTo called without current point, performing moveTo instead.");
            currentPath.moveTo(x, y); // Use raw x, y
            significantSegmentCount = 0; // Reset segment count
        } else {
            currentPath.lineTo(x, y); // Use raw x, y
            // Only increment if the line segment has non-zero length (using raw points)
            if (lastPoint != null && lastPoint.distanceSq(x, y) > 1e-12) {
                 significantSegmentCount++;
            }
        }
        lastPoint = new Point2D.Double(x, y); // Update lastPoint with raw EPS coordinates
        logger.log(Level.FINEST, "lineto: Raw ({0}, {1}) passed directly", new Object[]{x, y});
    }

    @Override
    public void curveTo(double x1, double y1, double x2, double y2, double x3, double y3) {
        // ---> Use RAW EPS coordinates <--- 
        // Point2D svgP1 = transformEpsToSvg(x1, y1); // Removed
        // Point2D svgP2 = transformEpsToSvg(x2, y2); // Removed
        // Point2D svgP3 = transformEpsToSvg(x3, y3); // Removed

        if (currentPath == null) {
             logger.log(Level.WARNING, "curveTo called before path initialized. Creating new path and moving to end point.");
             newPath();
             currentPath.moveTo(x3, y3); // Move to raw end point
             significantSegmentCount = 0;
             lastPoint = new Point2D.Double(x3, y3); // Store raw EPS
             return;
        }
        if (currentPath.getCurrentPoint() == null) {
             logger.log(Level.WARNING, "curveTo called without current point, performing moveTo instead to end point ({0},{1}).", new Object[]{x3, y3});
            currentPath.moveTo(x3, y3); // Move to raw end point
             significantSegmentCount = 0; // Reset segment count
        } else {
            currentPath.curveTo(x1, y1, x2, y2, x3, y3); // Use raw coordinates
             significantSegmentCount++; // Curve always counts as significant
        }
        lastPoint = new Point2D.Double(x3, y3); // Update lastPoint with raw EPS coordinates
        logger.log(Level.FINEST, "curveto: Raw ({0},{1}; {2},{3}; {4},{5}) passed directly",
                   new Object[]{x1, y1, x2, y2, x3, y3});
    }

    @Override
    public void closePath() {
        if (currentPath != null && currentPath.getCurrentPoint() != null) {
            currentPath.closePath();
            significantSegmentCount++; // Closing counts as significant
            logger.log(Level.FINEST, "closepath");
        } else {
             logger.log(Level.WARNING, "closePath called with no current point or null path.");
        }
    }

    @Override
    public void fill() {
        // --- Remove DIAGNOSTIC rectangle drawing ---
        /*
        try {
            java.awt.geom.Rectangle2D.Double testRect = new java.awt.geom.Rectangle2D.Double(10, 10, 50, 50);
            Paint originalPaint = svgGenerator.getPaint();
            svgGenerator.setPaint(Color.RED);
            svgGenerator.fill(testRect);
            svgGenerator.setPaint(originalPaint);
            logger.log(Level.FINE, "fill: Drew diagnostic red rectangle at (10,10) w=50, h=50");
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error during diagnostic fill operation", e);
        }
        */
        // --- Original fill logic ---
        try {
            if (currentPath != null && !currentPath.getPathIterator(null).isDone()) {
                logger.log(Level.FINE, "fill: path bounds={0}, CTM={1}", new Object[]{currentPath.getBounds2D(), svgGenerator.getTransform()});
                svgGenerator.fill(currentPath);
            } else {
                 logger.log(Level.WARNING, "fill: currentPath was empty or null when attempting to fill it.");
            }
            
            inspectBatikDom("[Immediately after filling CURRENT PATH]"); // Update context
            newPath();
            logger.log(Level.FINE, "fill: path reset");
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error during fill operation", e);
        }
    }

    @Override
    public void eoFill() {
         if (currentPath != null && currentPath.getCurrentPoint() != null) {
            logger.fine("eofill: path bounds=" + currentPath.getBounds2D());
            Path2D.Double eoPath = new Path2D.Double(currentPath);
            eoPath.setWindingRule(Path2D.WIND_EVEN_ODD);
            svgGenerator.fill(eoPath);
            currentPath = new Path2D.Double(); // Reset path after painting
            logger.fine("eofill: path reset");
         } else {
             logger.warning("eofill: called with no path or empty path.");
         }
    }

    @Override
    public void stroke() {
        if (currentPath == null || currentPath.getPathIterator(null).isDone()) {
            logger.log(Level.WARNING, "stroke: Attempted to stroke an empty or null path.");
            return;
        }
        try {
             // Rely on the CTM set on svgGenerator
            logger.log(Level.FINE, "stroke: path bounds={0}, CTM={1}", new Object[]{currentPath.getBounds2D(), svgGenerator.getTransform()});
            svgGenerator.draw(currentPath); // Pass original path
            inspectBatikDom("[Immediately after stroking CURRENT PATH]");
            newPath(); // Correct casing
            logger.log(Level.FINE, "stroke: path reset");
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error during stroke operation", e);
        }
    }

    @Override
    public void gsave() {
        if (svgGenerator == null) return;
        svgGenerator.create(); // Batik's way of saving graphics state

        // ---> Save current path state (ensure it's Path2D.Double) <---
        if (currentPath != null) {
            // Explicit cast needed if currentPath were just Path2D, but it's Path2D.Double
            pathStack.push((Path2D.Double) currentPath.clone());
            logger.log(Level.FINEST, "gsave: Pushed path state. Path stack depth: {0}", pathStack.size());
        } else {
            pathStack.push(new Path2D.Double()); // Push an empty path
            logger.log(Level.WARNING, "gsave: currentPath was null, pushed new empty path.");
        }
    }

    @Override
    public void grestore() {
        if (svgGenerator == null) return;

        // ---> Restore current path state (pop returns Path2D.Double) <---
        if (!pathStack.isEmpty()) {
            currentPath = pathStack.pop(); // Assign Path2D.Double back to currentPath
             significantSegmentCount = countSignificantSegments(currentPath); // Recalculate segment count
             lastPoint = currentPath.getCurrentPoint(); // Reset last point
             logger.log(Level.FINEST, "grestore: Popped path state. Path stack depth: {0}", pathStack.size());
        } else {
            logger.log(Level.SEVERE, "grestore: Attempted to pop from empty path stack!");
            newPath(); // Reset to a known state
        }

        svgGenerator.dispose(); // Batik's way of restoring graphics state
        logger.log(Level.FINEST, "grestore");
    }

    // Helper method to count segments (needed for restore)
    private int countSignificantSegments(Path2D path) {
        if (path == null) return 0;
        int count = 0;
        PathIterator pi = path.getPathIterator(null);
        double[] coords = new double[6];
        while (!pi.isDone()) {
            int segmentType = pi.currentSegment(coords);
            // Consider anything other than MOVE_TO as significant initially
            // (Refine if needed based on how isCurrentPathEffectivelyEmpty uses it)
            if (segmentType != PathIterator.SEG_MOVETO) {
                count++;
            }
            pi.next();
        }
        // A closed path adds a segment
        if (pi.getWindingRule() != PathIterator.WIND_NON_ZERO && count > 0) { // Check if closePath was added implicitly
             // This check is tricky; PathIterator doesn't easily reveal closePath.
             // Let's assume the count is roughly correct without explicit closePath check here.
        }
        return count;
    }

    // ---> SIMPLIFIED concatMatrix logic <---
    // No @Override
    private void concatMatrixLogic(double a, double b, double c, double d, double e, double f) {
        if (svgGenerator == null) {
             logger.log(Level.WARNING, "concatMatrix called before initialization.");
            return;
        }

        // Create an AffineTransform from the EPS matrix elements.
        // EPS matrix [a b c d e f] corresponds to AffineTransform(a, b, c, d, e, f)
        // Since our drawing coordinates are already transformed to the SVG system,
        // we apply this matrix directly to the svgGenerator CTM.
        AffineTransform epsMatrix = new AffineTransform(a, b, c, d, e, f);

        // Concatenate this matrix with the svgGenerator's current transform.
        svgGenerator.transform(epsMatrix); // Use transform() which concatenates

        logger.log(Level.FINE, "concatMatrix: Applied EPS Matrix=[{0}, {1}, {2}, {3}, {4}, {5}]. New SVG CTM: {6}",
                   new Object[]{a, b, c, d, e, f, svgGenerator.getTransform()});
    }

    // ---> Implement the interface method <---
    @Override
    public void concatMatrix(double[] matrix) {
         if (matrix != null && matrix.length == 6) {
             concatMatrixLogic(matrix[0], matrix[1], matrix[2], matrix[3], matrix[4], matrix[5]);
         } else {
             logger.log(Level.WARNING, "concatMatrix(double[]): Invalid matrix array passed.");
             // Optionally log the array contents if not null
             if (matrix != null) {
                 logger.log(Level.WARNING, "Matrix array contents: " + java.util.Arrays.toString(matrix));
             }
         }
    }

    // ---> Implement the required getCurrentPoint method <--- 
    @Override
    public Point2D getCurrentPoint() {
        if (currentPath != null && lastPoint != null) {
            // lastPoint now stores raw EPS coordinates
            // logger.log(Level.FINEST, "getCurrentPoint: returning raw EPS {0}", lastPoint);
            return lastPoint;
        }
        // logger.log(Level.FINEST, "getCurrentPoint: No current point known, returning null.");
        return null; // Consistent with Path2D.getCurrentPoint() returning null if path not started
    }

    // ---> Implement isCurrentPathEffectivelyEmpty method <--- 
    @Override
    public boolean isCurrentPathEffectivelyEmpty() {
        if (currentPath == null) {
            return true;
        }

        boolean hasDrawingSegment = false; // Flag to track if we found any drawing op
        Point2D startPoint = null;
        double[] coords = new double[6]; 

        PathIterator pi = currentPath.getPathIterator(null); 
        logger.log(Level.FINEST, "isCurrentPathEffectivelyEmpty: Starting iteration for path: {0}", currentPath.getBounds2D());

        while (!pi.isDone()) {
            int segmentType = pi.currentSegment(coords);
            logger.log(Level.FINEST, "  - Segment Type: {0}", segmentTypeToString(segmentType));
            switch (segmentType) {
                case PathIterator.SEG_MOVETO:
                    startPoint = new Point2D.Double(coords[0], coords[1]);
                    // Reset flag for new subpath? Maybe not necessary.
                    break;
                case PathIterator.SEG_LINETO:
                case PathIterator.SEG_QUADTO:
                case PathIterator.SEG_CUBICTO:
                    hasDrawingSegment = true;
                    // Optimization: can return false immediately
                    return false; 
                case PathIterator.SEG_CLOSE:
                    Point2D currentPos = currentPath.getCurrentPoint();
                    // Check if close actually creates a line segment
                    if (startPoint != null && currentPos != null &&
                        startPoint.distanceSq(currentPos) > 1e-12 ) { // Use tolerance
                       hasDrawingSegment = true;
                       // Optimization: can return false immediately
                       return false; 
                    }
                    // Otherwise, a close back to the start doesn't count as drawing
                    break;
                // No default case needed as other types shouldn't occur for Path2D.Double
            }
            pi.next();
        }

        // If we finish the loop without finding any drawing segment, it's empty.
        logger.log(Level.FINEST, "isCurrentPathEffectivelyEmpty: Finished iteration. hasDrawingSegment={0}. Returning {1}", new Object[]{hasDrawingSegment, !hasDrawingSegment});
        return !hasDrawingSegment; 
    }

    // Helper method to convert segment type constants to strings for logging
    private String segmentTypeToString(int segmentType) {
        switch (segmentType) {
            case PathIterator.SEG_MOVETO: return "SEG_MOVETO";
            case PathIterator.SEG_LINETO: return "SEG_LINETO";
            case PathIterator.SEG_QUADTO: return "SEG_QUADTO";
            case PathIterator.SEG_CUBICTO: return "SEG_CUBICTO";
            case PathIterator.SEG_CLOSE: return "SEG_CLOSE";
            default: return "UNKNOWN (" + segmentType + ")";
        }
    }

    // --- State Attribute Setters ---
    // These methods directly set Batik's state.

    private Color parseColor(double[] components) {
        // Reuse logic from old GraphicState or refine here
         if (components == null || components.length == 0) return Color.BLACK;
         try {
            if (components.length == 1) { // Grayscale
                float g = Math.max(0.0f, Math.min(1.0f, (float) components[0]));
                return new Color(g, g, g);
            } else if (components.length == 3) { // RGB
                 float r = Math.max(0.0f, Math.min(1.0f, (float) components[0]));
                 float g = Math.max(0.0f, Math.min(1.0f, (float) components[1]));
                 float b = Math.max(0.0f, Math.min(1.0f, (float) components[2]));
                return new Color(r, g, b);
            } else if (components.length == 4) { // CMYK -> RGB (simplistic)
                float c = Math.max(0.0f, Math.min(1.0f, (float) components[0]));
                float m = Math.max(0.0f, Math.min(1.0f, (float) components[1]));
                float y = Math.max(0.0f, Math.min(1.0f, (float) components[2]));
                float k = Math.max(0.0f, Math.min(1.0f, (float) components[3]));
                float r = (1.0f - c) * (1.0f - k);
                float g = (1.0f - m) * (1.0f - k);
                float b = (1.0f - y) * (1.0f - k);
                return new Color(Math.max(0.0f, Math.min(1.0f, r)), 
                                 Math.max(0.0f, Math.min(1.0f, g)), 
                                 Math.max(0.0f, Math.min(1.0f, b)));
            } else {
                logger.warning("Unsupported color component count: " + components.length);
                return Color.MAGENTA; // Error color
            }
        } catch (IllegalArgumentException e) {
             logger.warning("Invalid color value: " + Arrays.toString(components) + " -> " + e.getMessage());
             return Color.RED; // Error color
        }
    }

    @Override
    public void setGrayFill(double gray) {
        Color color = parseColor(new double[]{gray});
        svgGenerator.setPaint(color);
        logger.fine("setGrayFill: " + gray + " -> " + color);
    }

    @Override
    public void setGrayStroke(double gray) {
        // Batik uses Paint for both fill and stroke color
        // Need separate state tracking if PS allows different fill/stroke
        // For now, assuming setting stroke color also sets Paint
        Color color = parseColor(new double[]{gray});
        svgGenerator.setPaint(color);
         logger.fine("setGrayStroke: " + gray + " -> " + color + " (sets current Paint)");
    }

    @Override
    public void setRGBColorFill(double r, double g, double b) {
        Color color = parseColor(new double[]{r, g, b});
        svgGenerator.setPaint(color);
        logger.fine("setRGBColorFill: " + r +","+ g +","+ b + " -> " + color);
    }

    @Override
    public void setRGBColorStroke(double r, double g, double b) {
         Color color = parseColor(new double[]{r, g, b});
         svgGenerator.setPaint(color);
         logger.fine("setRGBColorStroke: " + r +","+ g +","+ b + " -> " + color + " (sets current Paint)");
    }

    @Override
    public void setCMYKColorFill(double c, double m, double y, double k) {
         Color color = parseColor(new double[]{c, m, y, k});
         svgGenerator.setPaint(color);
         logger.fine("setCMYKColorFill: " + c +","+ m +","+ y +","+ k + " -> " + color);
    }

    @Override
    public void setCMYKColorStroke(double c, double m, double y, double k) {
         Color color = parseColor(new double[]{c, m, y, k});
         svgGenerator.setPaint(color);
         logger.fine("setCMYKColorStroke: " + c +","+ m +","+ y +","+ k + " -> " + color + " (sets current Paint)");
    }

    @Override
    public void setLineWidth(double width) {
        Stroke currentStroke = svgGenerator.getStroke();
        float newWidth = Math.max(0.0f, (float) width); // Ensure non-negative
        if (currentStroke instanceof BasicStroke) {
            BasicStroke bs = (BasicStroke) currentStroke;
            // Create new stroke with updated width, preserving other attributes
            svgGenerator.setStroke(new BasicStroke(newWidth, bs.getEndCap(), bs.getLineJoin(), bs.getMiterLimit(), bs.getDashArray(), bs.getDashPhase()));
        } else {
            // If not a BasicStroke, just create a simple one
            svgGenerator.setStroke(new BasicStroke(newWidth));
        }
        logger.fine("setLineWidth: " + width);
    }

    @Override
    public void setLineCap(int cap) {
        Stroke currentStroke = svgGenerator.getStroke();
        int awtCap = (cap == 0) ? BasicStroke.CAP_BUTT : (cap == 1) ? BasicStroke.CAP_ROUND : BasicStroke.CAP_SQUARE;
        if (currentStroke instanceof BasicStroke) {
            BasicStroke bs = (BasicStroke) currentStroke;
            svgGenerator.setStroke(new BasicStroke(bs.getLineWidth(), awtCap, bs.getLineJoin(), bs.getMiterLimit(), bs.getDashArray(), bs.getDashPhase()));
        } else {
            svgGenerator.setStroke(new BasicStroke(1.0f, awtCap, BasicStroke.JOIN_MITER)); // Default width/join
        }
        logger.fine("setLineCap: " + cap);
    }

    @Override
    public void setLineJoin(int join) {
        Stroke currentStroke = svgGenerator.getStroke();
        int awtJoin = (join == 0) ? BasicStroke.JOIN_MITER : (join == 1) ? BasicStroke.JOIN_ROUND : BasicStroke.JOIN_BEVEL;
         if (currentStroke instanceof BasicStroke) {
            BasicStroke bs = (BasicStroke) currentStroke;
            svgGenerator.setStroke(new BasicStroke(bs.getLineWidth(), bs.getEndCap(), awtJoin, bs.getMiterLimit(), bs.getDashArray(), bs.getDashPhase()));
        } else {
            svgGenerator.setStroke(new BasicStroke(1.0f, BasicStroke.CAP_BUTT, awtJoin)); // Default width/cap
        }
        logger.fine("setLineJoin: " + join);
    }

    @Override
    public void setMiterLimit(double limit) {
        Stroke currentStroke = svgGenerator.getStroke();
        float newLimit = Math.max(1.0f, (float) limit); // Miter limit must be >= 1.0
         if (currentStroke instanceof BasicStroke) {
            BasicStroke bs = (BasicStroke) currentStroke;
            svgGenerator.setStroke(new BasicStroke(bs.getLineWidth(), bs.getEndCap(), bs.getLineJoin(), newLimit, bs.getDashArray(), bs.getDashPhase()));
        } else {
             // Setting miter limit implies BasicStroke
             svgGenerator.setStroke(new BasicStroke(1.0f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_MITER, newLimit));
        }
        logger.fine("setMiterLimit: " + limit);
    }

    @Override
    public void setDash(double[] pattern, double offset) {
        Stroke currentStroke = svgGenerator.getStroke();
        float[] floatPattern = null;
        if (pattern != null && pattern.length > 0) {
            floatPattern = new float[pattern.length];
            for (int i = 0; i < pattern.length; i++) {
                floatPattern[i] = Math.max(0.0f, (float) pattern[i]); // Dashes must be non-negative
            }
        } else {
             floatPattern = null; // null or empty array means solid line
        }
        float floatOffset = Math.max(0.0f, (float) offset);

         if (currentStroke instanceof BasicStroke) {
            BasicStroke bs = (BasicStroke) currentStroke;
            svgGenerator.setStroke(new BasicStroke(bs.getLineWidth(), bs.getEndCap(), bs.getLineJoin(), bs.getMiterLimit(), floatPattern, floatOffset));
        } else {
             svgGenerator.setStroke(new BasicStroke(1.0f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_MITER, 10.0f, floatPattern, floatOffset));
        }
        logger.fine("setDash: pattern=" + Arrays.toString(pattern) + " offset=" + offset);
    }
    
    // --- Helper Methods --- 
    private void inspectBatikDom() {
        inspectBatikDom("Default call");
    }

    /**
     * Inspects the Batik DOM to count specific elements, for debugging.
     * Now logs all immediate children of the root element and counts <path> and <rect>.
     * @param context A string describing when/where the inspection is happening.
     */
    private void inspectBatikDom(String context) {
        if (svgGenerator == null) {
             logger.log(Level.WARNING, "inspectBatikDom ({0}): svgGenerator is null, cannot inspect.", context);
             return;
        }
        // Use the DOM document associated with the generator
        Document doc = svgGenerator.getDOMFactory(); 
        if (doc == null) {
             logger.log(Level.WARNING, "inspectBatikDom ({0}): svgGenerator.getDOMFactory() returned null, cannot inspect.", context);
             return;
        }
        Element currentEffectiveRoot = doc.getDocumentElement();
        if (currentEffectiveRoot == null) {
            logger.log(Level.WARNING, "inspectBatikDom ({0}): Document root is null, cannot inspect.", context);
             return;
        }

        NodeList children = currentEffectiveRoot.getChildNodes();
        int elementCount = 0;
        List<String> childTags = new ArrayList<>();
        for (int i = 0; i < children.getLength(); i++) {
            Node node = children.item(i);
            if (node.getNodeType() == Node.ELEMENT_NODE) {
                elementCount++;
                childTags.add("<" + node.getNodeName() + ">");
            }
        }
        logger.log(Level.FINE, "inspectBatikDom ({0}): Root <{1}> has {2} child element(s): {3}", 
                     new Object[]{context, currentEffectiveRoot.getTagName(), elementCount, childTags});

        // Deeper inspection for <path> elements
        NodeList pathElements = currentEffectiveRoot.getElementsByTagNameNS(SVGDOMImplementation.SVG_NAMESPACE_URI, "path");
         logger.log(Level.FINE, "inspectBatikDom ({0}): Found {1} <path> element(s) under root.", new Object[]{context, pathElements.getLength()});
         for (int i = 0; i < Math.min(pathElements.getLength(), 5); i++) { // Log first few
            Node pathNode = pathElements.item(i);
            if (pathNode instanceof Element) {
                Element pathElement = (Element) pathNode;
                String dAttribute = pathElement.getAttributeNS(null, "d");
                String dSnippet = (dAttribute.length() > 80) ? dAttribute.substring(0, 80) + "..." : dAttribute;
                logger.log(Level.FINE, "inspectBatikDom ({0}): Path[{1}] d='{2}'", new Object[]{context, i, dSnippet});
            }
         }
         
        // Deeper inspection for <rect> elements
        NodeList rectElements = currentEffectiveRoot.getElementsByTagNameNS(SVGDOMImplementation.SVG_NAMESPACE_URI, "rect");
         logger.log(Level.FINE, "inspectBatikDom ({0}): Found {1} <rect> element(s) under root.", new Object[]{context, rectElements.getLength()});
         for (int i = 0; i < Math.min(rectElements.getLength(), 5); i++) { // Log first few
            Node rectNode = rectElements.item(i);
            if (rectNode instanceof Element) {
                Element rectElement = (Element) rectNode;
                logger.log(Level.FINE, "inspectBatikDom ({0}): Rect[{1}] x='{2}' y='{3}' w='{4}' h='{5}' fill='{6}'", 
                    new Object[]{context, i, 
                                 rectElement.getAttributeNS(null, "x"), 
                                 rectElement.getAttributeNS(null, "y"), 
                                 rectElement.getAttributeNS(null, "width"), 
                                 rectElement.getAttributeNS(null, "height"),
                                 rectElement.getAttributeNS(null, "fill")});
            }
         }
    }

     private String formatAffineTransform(java.awt.geom.AffineTransform transform) {
         // (Same implementation as before)
         double[] matrix = new double[6];
         transform.getMatrix(matrix);
         return String.format(Locale.ROOT, "[%.3f %.3f %.3f %.3f %.3f %.3f]",
             matrix[0], matrix[1], matrix[2], matrix[3], matrix[4], matrix[5]);
     }

    // --- Add helper method for ID generation ---
    private String generateManualId(String prefix) {
        String effectivePrefix = (prefix != null && !prefix.trim().isEmpty()) ? prefix.trim() : DEFAULT_ID_PREFIX;
        // Basic sanitization: replace non-alphanumeric/hyphen/underscore with underscore
        effectivePrefix = effectivePrefix.replaceAll("[^a-zA-Z0-9_-]", "_");
         // Ensure prefix doesn't start with a digit (invalid ID)
         if (!effectivePrefix.isEmpty() && Character.isDigit(effectivePrefix.charAt(0))) {
             effectivePrefix = DEFAULT_ID_PREFIX + "_" + effectivePrefix;
         }
         if (effectivePrefix.isEmpty()) { // Handle cases like invalid input resulting in empty string
            effectivePrefix = DEFAULT_ID_PREFIX;
         }
        return effectivePrefix + "-" + manualIdCounter.incrementAndGet();
    }

    // --- Add recursive helper for adding IDs ---
    private void addIdsToElementAndChildren(Element element) {
        if (element == null) {
            return;
        }
        // Generate and set ID for the current element
        String newId = generateManualId(element.getTagName());
        element.setAttributeNS(null, "id", newId);
        // logger.finest("Set ID '" + newId + "' on <" + element.getTagName() + ">"); // Verbose logging if needed

        // Recursively process child elements
        NodeList children = element.getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            Node node = children.item(i);
            if (node.getNodeType() == Node.ELEMENT_NODE) {
                addIdsToElementAndChildren((Element) node);
            }
        }
    }
} 