package com.convert2web;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Audits batch SVG viewBox against painted path/rect bounds in output coordinates.
 */
public final class ViewBoxAudit {
    private static final Pattern VIEWBOX = Pattern.compile("viewBox=\"0 0 ([^\"]+)\"");
    private static final Pattern PAGE_TRANSFORM = Pattern.compile(
            "<g transform=\"([^\"]+)\">");
    private static final Pattern PATH_D = Pattern.compile("\\sd=\"([^\"]+)\"");
    private static final Pattern FILL = Pattern.compile("fill=\"([^\"]+)\"");
    private static final Pattern STROKE = Pattern.compile("stroke=\"([^\"]+)\"");

    public static void main(String[] args) throws Exception {
        Path root = Path.of(args.length > 0 ? args[0]
                : "test/output/all-the-dita");
        List<String> overflow = new ArrayList<>();
        List<String> letterPage = new ArrayList<>();
        int checked = 0;
        int tight = 0;
        for (Path svg : Files.walk(root).filter(p -> p.toString().endsWith(".svg")).toList()) {
            String text = Files.readString(svg);
            if (text.contains("Generated by the Batik")) {
                continue;
            }
            Matcher vm = VIEWBOX.matcher(text);
            Matcher tm = PAGE_TRANSFORM.matcher(text);
            if (!vm.find() || !tm.find()) {
                continue;
            }
            String[] wh = vm.group(1).split("\\s+");
            double vw = Double.parseDouble(wh[0]);
            double vh = Double.parseDouble(wh[1]);
            Transform xf = Transform.parse(tm.group(1));

            double minX = Double.POSITIVE_INFINITY;
            double minY = Double.POSITIVE_INFINITY;
            double maxX = Double.NEGATIVE_INFINITY;
            double maxY = Double.NEGATIVE_INFINITY;
            boolean hasVisible = false;

            int pathIdx = 0;
            Matcher dm = PATH_D.matcher(text);
            while (dm.find()) {
                String attrs = snippetAround(text, dm.start(), 200);
                if (!isVisiblePaint(attrs)) {
                    pathIdx++;
                    continue;
                }
                for (double[] pt : PathPointParser.parse(dm.group(1))) {
                    double[] out = xf.apply(pt[0], pt[1]);
                    minX = Math.min(minX, out[0]);
                    minY = Math.min(minY, out[1]);
                    maxX = Math.max(maxX, out[0]);
                    maxY = Math.max(maxY, out[1]);
                    hasVisible = true;
                }
                pathIdx++;
            }

            if (!hasVisible) {
                continue;
            }
            checked++;
            if (vw < 200 && vh < 200) {
                tight++;
            }
            if (vw >= 500 && vh >= 700) {
                letterPage.add(svg.getFileName().toString());
            }
            double margin = 1.5;
            if (minX < -margin || minY < -margin || maxX > vw + margin || maxY > vh + margin) {
                overflow.add(String.format(
                        "%s viewBox=%.1fx%.1f bounds=[%.1f,%.1f]-[%.1f,%.1f] transform=%s",
                        root.relativize(svg), vw, vh, minX, minY, maxX, maxY, tm.group(1)));
            }
        }
        System.out.println("Checked " + checked + " VM SVGs, tight icons " + tight
                + ", letter-ish " + letterPage.size());
        System.out.println("Visible paint outside viewBox: " + overflow.size());
        overflow.stream().sorted().limit(30).forEach(System.out::println);
        if (overflow.size() > 30) {
            System.out.println("... and " + (overflow.size() - 30) + " more");
        }
    }

    private static String snippetAround(String text, int pos, int len) {
        int start = Math.max(0, pos - len);
        int end = Math.min(text.length(), pos + len);
        return text.substring(start, end);
    }

    private static boolean isVisiblePaint(String attrs) {
        Matcher fill = FILL.matcher(attrs);
        if (fill.find()) {
            String v = fill.group(1);
            if (!"none".equals(v) && !v.contains("255,255,255") && !v.contains("255,255,254")) {
                return true;
            }
        }
        Matcher stroke = STROKE.matcher(attrs);
        if (stroke.find()) {
            String v = stroke.group(1);
            if (!"none".equals(v)) {
                return true;
            }
        }
        return false;
    }

    private static final class Transform {
        private final double tx;
        private final double ty;
        private final double sy;
        private final double postTx;
        private final double postTy;

        private Transform(double tx, double ty, double sy, double postTx, double postTy) {
            this.tx = tx;
            this.ty = ty;
            this.sy = sy;
            this.postTx = postTx;
            this.postTy = postTy;
        }

        static Transform parse(String s) {
            double tx = 0;
            double ty = 0;
            double sy = 1;
            double postTx = 0;
            double postTy = 0;
            Matcher tr = Pattern.compile("translate\\(([-\\d.]+)(?:,([-\\d.]+))?\\)").matcher(s);
            int n = 0;
            while (tr.find()) {
                double a = Double.parseDouble(tr.group(1));
                double b = tr.group(2) != null ? Double.parseDouble(tr.group(2)) : 0;
                if (n == 0) {
                    tx = a;
                    ty = b;
                } else {
                    postTx = a;
                    postTy = b;
                }
                n++;
            }
            Matcher sc = Pattern.compile("scale\\(1,(-1)\\)").matcher(s);
            if (sc.find()) {
                sy = Double.parseDouble(sc.group(1));
            }
            return new Transform(tx, ty, sy, postTx, postTy);
        }

        double[] apply(double x, double y) {
            x += postTx;
            y += postTy;
            y *= sy;
            x += tx;
            y += ty;
            return new double[] {x, y};
        }
    }

    /** Minimal path point extractor for M/L/H/V/Z commands. */
    private static final class PathPointParser {
        private static List<double[]> parse(String d) {
            List<double[]> pts = new ArrayList<>();
            Pattern token = Pattern.compile("[MmLlHhVvZz]|[-]?\\d*\\.?\\d+");
            List<String> parts = new ArrayList<>();
            Matcher m = token.matcher(d);
            while (m.find()) {
                parts.add(m.group());
            }
            int i = 0;
            double cx = 0;
            double cy = 0;
            double sx = 0;
            double sy = 0;
            char cmd = 'M';
            while (i < parts.size()) {
                String t = parts.get(i);
                if (t.length() == 1 && Character.isLetter(t.charAt(0))) {
                    cmd = t.charAt(0);
                    i++;
                    continue;
                }
                switch (cmd) {
                    case 'M':
                    case 'L': {
                        double x = Double.parseDouble(parts.get(i++));
                        double y = Double.parseDouble(parts.get(i++));
                        cx = x;
                        cy = y;
                        sx = x;
                        sy = y;
                        pts.add(new double[] {x, y});
                        cmd = 'L';
                        break;
                    }
                    case 'm':
                    case 'l': {
                        double x = cx + Double.parseDouble(parts.get(i++));
                        double y = cy + Double.parseDouble(parts.get(i++));
                        cx = x;
                        cy = y;
                        if (cmd == 'm') {
                            sx = x;
                            sy = y;
                        }
                        pts.add(new double[] {x, y});
                        cmd = 'l';
                        break;
                    }
                    case 'H': {
                        double x = Double.parseDouble(parts.get(i++));
                        cx = x;
                        pts.add(new double[] {x, cy});
                        break;
                    }
                    case 'h': {
                        double x = cx + Double.parseDouble(parts.get(i++));
                        cx = x;
                        pts.add(new double[] {x, cy});
                        break;
                    }
                    case 'V': {
                        double y = Double.parseDouble(parts.get(i++));
                        cy = y;
                        pts.add(new double[] {cx, y});
                        break;
                    }
                    case 'v': {
                        double y = cy + Double.parseDouble(parts.get(i++));
                        cy = y;
                        pts.add(new double[] {cx, y});
                        break;
                    }
                    case 'Z':
                    case 'z':
                        cx = sx;
                        cy = sy;
                        break;
                    default:
                        i++;
                        break;
                }
            }
            return pts;
        }
    }
}
